  name: planc
  main: de.illy_trn.planc.PlanC
  version: 1.0
  api-version: '1.21'

  commands:
    spawn:
      description: Teleport to spawn
      usage: /spawn
    home:
      description: Teleport to your home
      usage: /home
    kit:
      description: give weapons
      usage: /kit